import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
PASTA_DADOS = BASE_DIR / "dados"
PASTA_SAIDA = BASE_DIR / "saida"

POSTGRES_USER = os.getenv("POSTGRES_USER", "admin_emive")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "emive_secure_password")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "postgres-db")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")
POSTGRES_DB = os.getenv("POSTGRES_DB", "disparos_emive")

DB_URL = os.getenv(
    "DATABASE_URL",
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)

CARTEIRA_INICIAL_ESTRUTURADA = {
    # --- Minas Gerais ---
    "F - BELO HORIZONTE": (6900, "FILIAL"),
    "F - GOV VALADARES": (161, "FILIAL"),
    "F - MONTES CLAROS": (84, "FILIAL"),
    "F - UBERLANDIA": (184, "FILIAL"),
    "F - DIVINOPOLIS": (544, "FILIAL"),
    "F - IPATINGA": (458, "FILIAL"),
    "F - UBA": (233, "FILIAL"),
    "F - JUIZ DE FORA": (749, "FILIAL"),

    # --- Filiais Nacionais (Padrão Oficial) ---
    "FILIAL EMIVE CAMPOS DOS GOYTACAZES": (304, "FILIAL"),
    "FILIAL EMIVE RIO DE JANEIRO": (1592, "FILIAL"),
    "FILIAL EMIVE NITEROI": (429, "FILIAL"),
    "FILIAL EMIVE VITORIA": (1490, "FILIAL"),
    "FILIAL EMIVE LINHARES": (660, "FILIAL"),
    "FILIAL EMIVE MANAUS": (1221, "FILIAL"),
    "FILIAL EMIVE PORTO VELHO": (31, "FILIAL"),
    "FILIAL EMIVE BELEM": (237, "FILIAL"),
    "FILIAL EMIVE FORTALEZA": (1030, "FILIAL"),
    "FILIAL EMIVE SAO LUIZ": (588, "FILIAL"),
    "FILIAL EMIVE NATAL": (19, "FILIAL"),
    "FILIAL EMIVE JOAO PESSOA": (931, "FILIAL"),
    "FILIAL EMIVE CAMPINA GRANDE": (200, "FILIAL"),
    "FILIAL EMIVE RECIFE": (950, "FILIAL"),
    "FILIAL EMIVE CARUARU": (369, "FILIAL"),
    "FILIAL EMIVE GOIANIA": (885, "FILIAL"),
    "FILIAL EMIVE BRASILIA": (1138, "FILIAL"),
    "FILIAL EMIVE CAMPO GRANDE": (1305, "FILIAL"),
    "FILIAL EMIVE CUIABA": (684, "FILIAL"),
    "FILIAL EMIVE PETROLINA": (61, "FILIAL"),
    "FILIAL EMIVE MACEIO": (832, "FILIAL"),
    "FILIAL EMIVE FEIRA DE SANTANA": (95, "FILIAL"),
    "FILIAL EMIVE SALVADOR": (476, "FILIAL"),
    "FILIAL EMIVE ARACAJU": (520, "FILIAL"),
    "FILIAL EMIVE TERESINA": (4, "FILIAL"),
    "FILIAL EMIVE SP BERRINI": (648, "FILIAL"),
    "FILIAL EMIVE SP FARIA LIMA": (711, "FILIAL"),
    "FILIAL EMIVE SAO CAETANO DO SUL": (1360, "FILIAL"),
    "FILIAL EMIVE CAMPINAS": (1244, "FILIAL"),
    "FILIAL EMIVE TATUAPE": (389, "FILIAL"),
    "FILIAL EMIVE SAO JOSE DOS CAMPOS": (730, "FILIAL"),
    "FILIAL EMIVE RIBEIRAO PRETO": (252, "FILIAL"),
    "FILIAL EMIVE PORTO ALEGRE": (495, "FILIAL"),
    "FILIAL EMIVE CURITIBA": (241, "FILIAL"),
    "FILIAL EMIVE LONDRINA": (29, "FILIAL"),
    "FILIAL EMIVE JOINVILLE": (98, "FILIAL"),
    "FILIAL EMIVE BALNEARIO CAMBORIU": (271, "FILIAL"),
    "FILIAL EMIVE FLORIANOPOLIS": (514, "FILIAL"),

    # --- Especiais / Grandes Contas ---
    "SMART": (32346, "ESPECIAL"),
    "MANUTENÇÃO REGIONAL": (7115, "ESPECIAL"),
    "REDES": (1117, "ESPECIAL"),
    "TOTENS": (175, "ESPECIAL"),
    "SMART P": (97, "ESPECIAL"),
    "DGP": (290, "ESPECIAL"),
}

CARTEIRA_INICIAL = {k: v[0] for k, v in CARTEIRA_INICIAL_ESTRUTURADA.items()}